name: sms_retriever_v2
description: A new Flutter plugin to retrieve the SMS on Android using SMS Retrieval API(Fix)
version: 0.0.20
author: Foked By Felipe Araujo <felipe.araujo@bompracredito.com.br>
homepage: https://github.com/BomPraCredito/sms_retriever

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    androidPackage: com.debut.sms_retriever
    pluginClass: SmsRetrieverPlugin


